#include "rayTracer.hpp"

#include <ros/ros.h>    // this is just to display warnings, can be removed in the end

/********************************************************
 *  Class Vec2
 ********************************************************/

Vec2::Vec2(float x, float y) : x(x), y(y) {}

Vec2::~Vec2() = default;

float Vec2::getX() const {
    return x;
}

void Vec2::setX(float x) {
    Vec2::x = x;
}

float Vec2::getY() const {
    return y;
}

void Vec2::setY(float y) {
    Vec2::y = y;
}

Vec2 Vec2::operator+(const Vec2& vec) {
    return Vec2(x+vec.x,y+vec.y);
}

Vec2 Vec2::operator-(const Vec2& vec) {
    return Vec2(x-vec.x, y-vec.y);
}

Vec2 Vec2::operator*(const float& factor) {
    return Vec2(x*factor, y*factor);
}

/********************************************************
 *  Class Ray
 ********************************************************/

Ray::Ray(const Vec2 &start, const Vec2 &dir) : start(start), dir(dir) {
   }

Ray::~Ray() = default;

const Vec2 &Ray::getStart() const {
    return start;
}

void Ray::setStart(const Vec2 &start) {
    Ray::start = start;
}

const Vec2 &Ray::getDir() const {
    return dir;
}

void Ray::setDir(const Vec2 &dir) {
    Ray::dir = dir;
}

float Ray::getLength() {
    // TODO
    std::cerr << "getLength in Class Ray is not yet implemented" << std::endl;
    return 0;
}

Vec2 Ray::getCenter() {
    // TODO
    std::cerr << "getCenter in Class Ray is not yet implemented" << std::endl;
    return Vec2(0, 0);
}

void Ray::setOccuGridFields(nav_msgs::OccupancyGrid &inputGrid) {
    // TODO
    std::cerr << "setOccuGridFields in Class Ray is not yet implemented" << std::endl;
}

/********************************************************
 *  Class RayTracer
 ********************************************************/
/*
 * Breef:
 * This is the Constructor for the RayTracer.
 * It Constructs numberOfRays Rays.
 * All Rays will start at RAYTRACER_RAY_START_X and RAYTRACER_RAY_START_Y.
 * Direction of the generated Rays:
 * The direction of the Rays will be equally distributed between 0 and 180 degrees.
 * 0 degrees and 180 degrees are not included.
 * The Vector will be scalled, so that the abs value of the coordinate with lower abs value will be 1
 * @param numberofRays number of rays generated by the Ray Tracer
 */
RayTracer::RayTracer(int numberOfRays){

    // exception: numberOfRays is to low
    if(numberOfRays < 1){
        throw std::range_error("numberOfRays in RayTracer::Raytracer() is out of Range");
    }

    // init rays
    std::vector<Ray> rayVec;
    for(int i = 1; i <= numberOfRays; i++){
        /*
         * Create 1 Ray per loop cycle
         */
        // all rays should have the same angle to each other, so coordinates from the unit circle will be used
        float angle = ((float)i/(float)(numberOfRays + 1) * M_PIf32);
        Vec2 dir(cos(angle),sin(angle));
        // scale dir to set lower coordinate to +1 or -1
        // except if one coordinate is 0
        if(abs(dir.getX()) >= 0.0001 && abs(dir.getY() >= 0.0001)) {
            if (abs(dir.getX()) < abs(dir.getY())) {
                dir = dir * (1 / abs(dir.getX()));
            } else {
                dir = dir * (1 / abs(dir.getY()));
            }
        }
        Ray ray(Vec2(RAYTRACER_RAY_START_X, RAYTRACER_RAY_START_Y),dir);
        rayVec.push_back(ray);
    }
    this->rays = rayVec;

    // init inputGrid

    // init outputGrid

}

const std::vector<Ray> &RayTracer::getRays() const {
    return rays;
}

Ray RayTracer::getLongestRay() {
    // TODO
    std::cerr << "getLongestRay in Class RayTracer is not yet implemented" << std::endl;
    return Ray(Vec2(0,0), Vec2(0,0));
}

const nav_msgs::OccupancyGrid &RayTracer::getInputGrid() const {
    return inputGrid;
}

void RayTracer::setInputGrid(const nav_msgs::OccupancyGrid &inputGrid) {
    RayTracer::inputGrid = inputGrid;
}

const nav_msgs::OccupancyGrid &RayTracer::getOutputGrid() const {
    return outputGrid;
}

void RayTracer::setOutputGrid(const nav_msgs::OccupancyGrid &outputGrid) {
    RayTracer::outputGrid = outputGrid;
}








